steps:
- name: 'Install dependencies'
  args: ['npm', 'install']
- name: 'Build the app'
  args: ['npm', 'run', 'build']
- name: 'Deploy the app'
  args: ['gcloud', 'run', 'deploy', 'chess', '--image', 'gcr.io/chess-412709/chess:latest']

images: ['gcr.io/chess-412709/chess:latest']
