steps:

# Step 0: FRONTEND copy only build and deploy cloud app frontend
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  dir: '/'
  args: 
    - '-c'
    - |
      cd ..
      cp app-production-build.yaml /build
      cd /build
      gcloud app deploy
  timeout: '1600s'
